USE noglue_blog;

INSERT INTO posts(name,title,body,created_at,modified_at) VALUES
('far-far-away-something1','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
('far-far-away-something2','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
('far-far-away-something3','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
('far-far-away-something4','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
('far-far-away-something5','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP());

INSERT INTO users (username,password,`level`,created_at,modified_at) VALUES ('admin','$2a$12$adminadminadminadminaOS4Mw069IfjzJ2NobRHRQJPgv656fj0q',0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
INSERT INTO users (username,password,`level`,created_at,modified_at) VALUES ('someone','password',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
INSERT INTO users (username,password,`level`,created_at,modified_at) VALUES ('anotherone','password',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
INSERT INTO users (username,password,`level`,created_at,modified_at) VALUES ('adude','password',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
INSERT INTO users (username,password,`level`,created_at,modified_at) VALUES ('aguy','password',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
